//**********************************************************************`
//* This is an include file generated by Message Compiler.             *`
//*                                                                    *`
//* Copyright (c) Microsoft Corporation. All Rights Reserved.          *`
//**********************************************************************`
#pragma once

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// Provider "BLESniffRaw" event count 1
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

// Provider GUID = e3c99c07-0ea4-463d-b4f6-c9724428d18c
EXTERN_C __declspec(selectany) const GUID BLESniffRaw = {0xe3c99c07, 0x0ea4, 0x463d, {0xb4, 0xf6, 0xc9, 0x72, 0x44, 0x28, 0xd1, 0x8c}};

#ifndef BLESniffRaw_Traits
#define BLESniffRaw_Traits NULL
#endif // BLESniffRaw_Traits

//
// Channel
//
#define BLESniffChannel 0x10

//
// Opcodes
//
#define BLESniffOpCode 0xa

//
// Tasks
//
#define BLESniffTask 0x1

//
// Keyword
//
#define BLESniffKeyword 0x1

//
// Event Descriptors
//
EXTERN_C __declspec(selectany) const EVENT_DESCRIPTOR BLERawMessage = {0x3ed, 0x1, 0x10, 0x4, 0xa, 0x1, 0x8000000000000001};
#define BLERawMessage_value 0x3ed

#define MSG_BLERawMsg                        0x90000001L
